### ISSUE TITLE
css 体积过大，影响页面加载

### ISSUE THREAD

**Issue by foxhsx** [cyyjs/milkdown-vue#3]
Hi, 你好！
最近在使用 milkdown-vue 时遇到一个问题，那就是包中的源文件体积都很大，js 有2.9M，css 有 1.3M，在使用 gzip 压缩后，js 还有七百多k，而 css 还有九百多 kb。我查看了插件的[示例 demo](https://cyyjs.github.io/milkdown-vue/)，发现其中的 css 只有 9.4kb，请问这是怎么做到的呢？在哪里可以进行优化呢？
请帮忙解答一下，万分感谢🙏

**Comment by cyyjs** [comment]
可以更新到`1.0.3`版本解决

**Comment by hesanjin** [comment]
> 可以更新到`1.0.3`版本解决

好的，多谢
